services:
  mariadb:
    build: requirements/mariadb/.
    image: mariadb:v0
    container_name: mariadb
    restart: unless-stopped
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      inception:

  wordpress:
    build:
      context: ./requirements/wordpress/
    image: wordpress:v0
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      URL: ${URL}
      TITLE: ${TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_ROLE: ${WP_ROLE}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_HOST_PORT: ${DB_HOST_PORT}
      DB_NAME: ${DB_NAME}
      WP_ADMIN_PASSWORD_FILE: /run/secrets/wp_admin_password
      WP_USER_PASSWORD_FILE: /run/secrets/wp_user_password
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - wp_admin_password
      - wp_user_password
      - db_password
    networks:
      inception:
    volumes:
      - /home/merrahal/data/web:/var/www/html
    init: true
  nginx:
    build:
      context: ./requirements/nginx/
      args:
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        LOCALITY: ${LOCALITY}
        ORGANIZATION: ${ORGANIZATION}
        UNIT: ${UNIT}
        COMMON_NAME: ${COMMON_NAME}
    image: nginx:v0
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - mariadb
      - wordpress
    ports:
      - "443:443"
    volumes:
      - /home/merrahal/data/web:/var/www/html
    networks:
      inception:
    init: true

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/merrahal/data/mariadb

networks:
  inception: